CUDA_VISIBLE_DEVICES=$1 python main.py \
	--id=road_runner.deploy_dqn_f0.98_count_seed_$2 \
	--env-type=atari \
	--game=road_runner \
	--deploy-policy=dqn-feature \
	--feature-threshold=0.98 \
        --seed=$2 \
	--count-base-bonus=0.01 \
	--checkpoint-interval=100000
